name = "Qino"
author = "GaiusRed"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "785da67d798e73d2aaf3cf9912a8839c2c64c4f2434d39eccd6f92d1e71befe0"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
